[tool.poetry]
name = "sample-app"
version = "0.1.0"
description = "App A project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
# 다른 필요 라이브러리들 추가

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"